### ISSUE TITLE
How can I use the custom models to set up Claude 3.7 Sonnet?

### ISSUE THREAD

**Issue by mk1123** [intellibar/main#93]
Hi! I was excited to use the [custom models feature](https://docs.intellibar.app/using-custom-models) to try setting up Claude 3.7 Sonnet in Intellibar, but I can't figure out the right combination of `url` and `id` to use for Anthropic's API for this to work within Intellibar. Any guidance here?

**Comment by astoilkov** [comment]
Here's the correct configuration:
```yaml
url: https://api.anthropic.com
id: claude-3-7-sonnet-latest
name: 3.7 Sonnet
apiType: anthropic
apiKey: ....your api key here...
```

Can you share what was that you weren't able to figure out?

BTW, we'll release an update tomorrow that will include Claude 3.7 Sonnet.
